version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y cmake git gcc-7
            apt-get install -y libsigc++-2.0-dev qtbase5-dev libqt5opengl5-dev libsuitesparse-dev libboost1.62-dev libeigen3-dev flex bison re2c
      - run:
          name: Prepare build directory
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            mkdir build
            cd build
            cmake ..
      - run:
          name: Build
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/build
            make -j2
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - $CIRCLE_WORKING_DIRECTORY/build

  test:
    docker:
      - image: ubuntu:bionic
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y cmake
      - run:
          name: test  libfemp
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/build
            cd libfemp
            ctest

workflows:
  version: 2
  unscheduled:
    jobs:
      - build
      - test:
          requires:
            - build
