version: 2.1

jobs:
  install:
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y cmake git
            apt-get install -y libsigc++-2.0-dev qtbase5-dev libqt5opengl5-dev libsuitesparse-dev libboost1.62-dev libeigen3-dev flex bison re2c

  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: Prepare build directory
          command: |
            mkdir build
            cd build
            cmake ..
      - run:
          name: Build
          command: |
            cd build
            make
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build

  test:
    docker:
      - image: ubuntu:bionic
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: test  libfemp
          command: |
            cd build/libfemp
            ctest

workflows:
  version: 2
  unscheduled:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
